# Freemarker / Http
spring :
    http :
        encoding :
            charset : UTF-8
            enabled : true
    freemarker :
        cache : false
        charset : UTF-8
        check-template-location : true
        content-type : text/html
        prefix : /_template/
        suffix : .ftl
        template-loader-path : classpath:/templates/_freemarker/
        settings :
            default_encoding : UTF-8
            datetime_format : yyyy-MM-dd
            number_format : 0.###

    cache :
        ehcache :
        config : classpath:/conf/cache/ehcache-config.xml

---

# Server Setting
server :
    session :
        timeout : 1800
    tomcat :
        uri-encoding : UTF-8
    servlet-path : /*
    port: 8080

spring:
    profiles:
      active: local
    first :
        datasource:
            #jndi-name : java:/comp/env/jdbc/MySqlDS
            url : jdbc:mysql://localhost:3306/BAMONS2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000
    second :
        datasource:
            #jndi-name : java:/comp/env/jdbc/MySqlDS
            url : jdbc:mysql://localhost:3306/BAMONS2?useUnicode=true&characterEncoding=UTF-8&useSSL=true
            driver-class-name : com.mysql.jdbc.Driver
            username : root
            password : 1111
            type : javax.sql.DataSource
            maxActive : 50
            maxIdle : 0
            maxWait : -1
            validationQuery : SELECT 1
            testWhileIdle : true
            timeBetweenEvictionRunsMillis : 1800000

# Actuator 읽기 인증 제거
management :
    security :
        enabled : false